### ISSUE TITLE
Autocomplete on tab not working

### ISSUE THREAD

**Issue by 533kr** [Algid/FabricEmotes#3]
By the mod description I got the impression there's supposed to be an autocomplete/suggestion feature similar to what the console uses, but that's absent for me. I have the version for 1.18.2 and otherwise the mod works great, exactly as expected.

**Comment by Algid** [comment]
Hm interesting, it seems to work okay for me - if you type `:` then press TAB to autocomplete it *should* then autocomplete the emotes like so:
![image](https://user-images.githubusercontent.com/5259999/179635665-c1008bae-83fa-4344-901f-c39ab8ec68e1.png)
this seems to work for me with the latest version of Fabric in Minecraft 1.18.2 - it may be a mod conflict if it isn't working for you still?

**Comment by Algid** [comment]
Closing for now due to no response & cannot recreate issue
