### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by unleashed7** [Algid/FabricEmotes#6]
It's such an awesome mod, too bad there's no 1.19+ support

**Comment by Algid** [comment]
I haven't done any further development on this project as the AOF team made a fork, it can be found here:
https://www.curseforge.com/minecraft/mc-mods/aof-emotes

Hopefully it can live on through them, glad I could help bring emotes to Fabric!

**Comment by unleashed7** [comment]
Oh, thank you for that! And for your contribution by making this mod!
